#name: Docker_Image CI
#
#on:
#  push:
#    branches: ["master"]
#  pull_request:
#    branches: ["master"]
#
#
#jobs:
#  build:
#    runs-on: ubuntu-22.04
#    strategy:
#      matrix:
#        python-version: ["3.7", "3.8", "3.9", "3.10"]
#    steps:
#      - uses: actions/checkout@v3
#      - name: Log in to Docker Hub
#        uses: docker/oumaimanijaoui/oumaima_nijaoui
#        with:
#          python-version: ${{ matrix.python-version }}
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#      - name: Build the Docker image
#        run: docker build . --file Dockefile --tag OumaimaNijaoui/Oumaima_virtualisation:${GITHUB_SHA::8}
#
#      - name: Push Docker Image to Docker Hub
#        run: docker push ${{ secrets.DOCKER_USERNAME}}/oumaimanijaoui/oumaima_nijaoui:${GITHUB_SHA::8}

